//
//  UIColor+Color.swift
//
//  Generated by Zeplin on 5/23/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func MRSandBrownColor() -> UIColor {
		return UIColor(red: 211.0 / 255.0, green: 150.0 / 255.0, blue: 104.0 / 255.0, alpha: 1.0)
	}

	class func MRBrownishColor() -> UIColor {
		return UIColor(red: 160.0 / 255.0, green: 98.0 / 255.0, blue: 90.0 / 255.0, alpha: 1.0)
	}

	class func MRBarneyColor() -> UIColor {
		return UIColor(red: 201.0 / 255.0, green: 28.0 / 255.0, blue: 187.0 / 255.0, alpha: 1.0)
	}

	class func MRDarkSalmonColor() -> UIColor {
		return UIColor(red: 204.0 / 255.0, green: 113.0 / 255.0, blue: 93.0 / 255.0, alpha: 1.0)
	}

	class func MRWhiteColor() -> UIColor {
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	class func MRPaleColor() -> UIColor {
		return UIColor(red: 255.0 / 255.0, green: 239.0 / 255.0, blue: 214.0 / 255.0, alpha: 1.0)
	}

	class func MRDarkSandColor() -> UIColor {
		return UIColor(red: 166.0 / 255.0, green: 145.0 / 255.0, blue: 84.0 / 255.0, alpha: 1.0)
	}

	class func MRCharcoalGreyColor() -> UIColor {
		return UIColor(red: 61.0 / 255.0, green: 52.0 / 255.0, blue: 66.0 / 255.0, alpha: 1.0)
	}

	class func MRPinkishGreyColor() -> UIColor {
		return UIColor(white: 204.0 / 255.0, alpha: 1.0)
	}

	class func MRPaleGoldColor() -> UIColor {
		return UIColor(red: 251.0 / 255.0, green: 197.0 / 255.0, blue: 111.0 / 255.0, alpha: 1.0)
	}

	class func MRDenimBlueColor() -> UIColor {
		return UIColor(red: 59.0 / 255.0, green: 89.0 / 255.0, blue: 152.0 / 255.0, alpha: 1.0)
	}

	class func MRPaleTwoColor() -> UIColor {
		return UIColor(red: 254.0 / 255.0, green: 241.0 / 255.0, blue: 220.0 / 255.0, alpha: 1.0)
	}

	class func MRRedColor() -> UIColor {
		return UIColor(red: 230.0 / 255.0, green: 12.0 / 255.0, blue: 12.0 / 255.0, alpha: 1.0)
	}

	class func MRSeafoamBlueColor() -> UIColor {
		return UIColor(red: 110.0 / 255.0, green: 184.0 / 255.0, blue: 204.0 / 255.0, alpha: 1.0)
	}

	class func MRBubblegumColor() -> UIColor {
		return UIColor(red: 255.0 / 255.0, green: 108.0 / 255.0, blue: 197.0 / 255.0, alpha: 1.0)
	}

	class func MRRobinsEggBlueColor() -> UIColor {
		return UIColor(red: 147.0 / 255.0, green: 225.0 / 255.0, blue: 246.0 / 255.0, alpha: 0.0)
	}

	class func MRLightblueColor() -> UIColor {
		return UIColor(red: 99.0 / 255.0, green: 215.0 / 255.0, blue: 246.0 / 255.0, alpha: 1.0)
	}

	class func MRDarkSlateBlueColor() -> UIColor {
		return UIColor(red: 14.0 / 255.0, green: 53.0 / 255.0, blue: 64.0 / 255.0, alpha: 1.0)
	}
    
    class func MRWaterBlueColor() -> UIColor {
        return UIColor(red: 11.0 / 255.0, green: 151.0 / 255.0, blue: 189.0 / 255.0, alpha: 1.0)
    }
    
}
